src/InfoGames/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using InfoGames.Helper;
using InfoGames.Models;
using InfoGames.Data;
using System.Diagnostics;

namespace InfoGames.Controllers;

public class LoginController : Controller {
    private readonly ISessao _sessao;
    private readonly ApplicationDbContext _db;

    public LoginController(ISessao sessao, ApplicationDbContext db) {

        _sessao = sessao;
        _db = db;
    }

    public IActionResult Index() {
        // Caso usuario esteja logado não voltar ao login
        //if (_sessao.BuscarSessaoDoUsuario() != null) return RedirectToAction("Index", "Home");
        return View();
    }


    // GET: Login/Create
    public IActionResult Create() {
        return View();
    }

    // GET: Login/Reset
    public IActionResult Reset() {
        return View();
    }

    public IActionResult Sair() {
        _sessao.RemoverSessaoUsuario();
        return RedirectToAction("Deslogado", "Home");
    }
    public Usuario? BuscarPorLogin(string email) {
        return _db.Usuario.FirstOrDefault(m => m.Email == email);
    }

    [HttpPost]
    public IActionResult Entrar(LoginModel loginModel) {
        try {

            if (ModelState.IsValid) {
                Usuario? usuario = BuscarPorLogin(loginModel.Login);
                Debug.WriteLine(usuario?.Email);
                if (usuario != null) {
                    if (usuario.SenhaValida(loginModel.Senha)) {
                        _sessao.CriarSessaoUsuario(usuario);
                        return RedirectToAction("Index", "Home");
                    }

                    TempData["MensagemErro"] = $"Senha inválida. Por favor, tente novamente.";
                    return View("Index");
                }
                TempData["MensagemErro"] = $"Usuário e/ou senha inválido(s). Por favor, tente novamente.";


            }
            ViewBag.nomeUsuario = loginModel.Login;
            return View("Index");
        } catch (Exception erro) {
            TempData["MensagemErro"] = $"Não conseguimos realizar seu login, tente novamente, detalhe do erro: {erro.Message}";
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Reset(LoginModel loginModel) {
        try {
            if (ModelState.IsValid) {
                Usuario? usuario = BuscarPorLogin(loginModel.Login);

                if (usuario != null) {
                    usuario.AtualizarSenha(loginModel.Senha);
                    _db.Update(usuario);
                    await _db.SaveChangesAsync();
                    TempData["AvisoSenha"] = $"Senha alterada com Sucesso! Considere agora se conectar.";
                    return View("Index");
                }
                TempData["MensagemErro"] = $"Email inválido. Por favor, tente novamente.";


            }

            return View("Index");
        } catch (Exception erro) {
            TempData["MensagemErro"] = $"Não conseguimos realizar seu login, tente novamente, detalhe do erro: {erro.Message}";
            return RedirectToAction("Index");
        }
    }
}

src/InfoGames/Controllers/LojaController.cs
using InfoGames.Data;
using InfoGames.Models;
using Microsoft.AspNetCore.Mvc;


namespace InfoGames.Controllers {
    public class LojaController : Controller {
        private readonly ApplicationDbContext _db;
        public LojaController(ApplicationDbContext db) {
            _db = db;
        }
        public IActionResult Index() {
            List<LojaModel> objLojasList = _db.Lojas.ToList();

            ViewBag.listaLoja = objLojasList;

            return View();
        }

        public IActionResult Form(string method, string id) {
            if (method == "add") {
                return View();
            } else if (method == "edit" && !string.IsNullOrEmpty(id)) {
                var obj = _db.Lojas.Find(id);
                if (obj == null) {
                    return NotFound();
                }
                return View(obj);
            } else {
                return BadRequest();
            }
        }

        public IActionResult Add(LojaModel obj) {
            obj.Id = Guid.NewGuid().ToString();
            if (ModelState.IsValid) {
                _db.Lojas.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Form");
        }


        public IActionResult Edit(LojaModel obj) {
            if (ModelState.IsValid) {
                _db.Lojas.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(string id) {
            if (id == null || id == "") {
                return NotFound();
            }
            var obj = _db.Lojas.Find(id);
            if (obj == null) {
                return NotFound();
            }
            _db.Lojas.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

src/InfoGames/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using InfoGames.Models;
using InfoGames.Data;

namespace InfoGames.Controllers {
    public class UsuariosController : Controller {
        private readonly ApplicationDbContext _db;

        public UsuariosController(ApplicationDbContext db) {
            _db = db;
        }

        // GET: Usuarios
        public IActionResult Index() {
            List<Usuario> objUsuariosList = _db.Usuario.ToList();
            ViewBag.listaUsuarios = objUsuariosList;
            return View();
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _db.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null) {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create() {
            return View();
        }



        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,NomeDeUsuario,Senha,Email,Token,DataNascimento,ContaSuspensa,ContaRestrita,SteamIdVinculado,EmailVerificado")] Usuario usuario) {
            if (ModelState.IsValid) {
                _db.Add(usuario);
                await _db.SaveChangesAsync();

                // Verificar se o cabeçalho Referer está presente na requisição
                if (Request.Headers.ContainsKey("Referer")) {
                    // Obter o URL da página anterior a partir do cabeçalho Referer
                    string returnUrl = Request.Headers["Referer"].ToString();

                    // Adiciona a mensagem na sessão
                    TempData["Mensagem"] = "Usuário cadastrado com sucesso!";


                    // Redirecionar de volta para a página anterior
                    return Redirect(returnUrl);
                } else {
                    // Se o cabeçalho Referer não estiver presente, redirecione para uma página padrão
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _db.Usuario.FindAsync(id);
            if (usuario == null) {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,NomeDeUsuario,Senha,Email,Token,DataNascimento,ContaSuspensa,ContaRestrita,SteamIdVinculado,EmailVerificado")] Usuario usuario) {
            if (id != usuario.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _db.Update(usuario);
                    await _db.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!UsuarioExists(usuario.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _db.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null) {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var usuario = await _db.Usuario.FindAsync(id);
            if (usuario != null) {
                _db.Usuario.Remove(usuario);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id) {
            return _db.Usuario.Any(e => e.Id == id);
        }
    }
}

src/InfoGames/Views/Shared/Components/Menu/Default.cshtml
@using InfoGames.Helper
@inject ISessao _sessao

@{
    var usuarioLogado = _sessao.BuscarSessaoDoUsuario();
    var nomeDeUsuario = usuarioLogado?.NomeDeUsuario ?? "Visitante";
}

<head>
    <style>
        .navbar-custom {
            background-color: rgba(26, 22, 145, 0.7); /* Azul escuro com transparência */
            border: none; /* Remove as bordas */
            padding: 20px;
            margin: 30px;
            border-radius: 10px;
        }

            .navbar-custom .navbar-brand,
            .navbar-custom .nav-link,
            .navbar-custom .form-control {
                color: #ffffff; /* Cor branca para o texto */
            }

                .navbar-custom .nav-link:hover {
                    color: #cccccc; /* Cor cinza claro para o texto ao passar o mouse */
                }

            .navbar-custom .navbar-toggler {
                border-color: rgba(255, 255, 255, 0.1); /* Transparência para o botão de toggler */
            }

            .navbar-custom .navbar-toggler-icon {
                background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba%28white, 0.5%29' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
            }

            .navbar-custom .navbar-nav .nav-item {
                margin-right: 15px; /* Espaçamento horizontal entre os itens */
            }

                .navbar-custom .navbar-nav .nav-item + .nav-item {
                    margin-left: 15px; /* Espaçamento horizontal entre os itens */
                }

                .navbar-custom .navbar-nav .nav-item a {
                    margin-bottom: 5px; /* Espaçamento vertical entre os links */
                }
    </style>
</head>

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom box-shadow mb-3 ml-2">
    <div class="">
        <img src="~/Logo/LOGO FAVICON WHITE.png" alt="Logo da Empresa" class="img-fluid" style="height: 50px; width: 50px;">
    </div>
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Olá, @nomeDeUsuario</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <form class="form-inline " asp-controller="Jogo" asp-action="Index" method="get" onsubmit="return false;">
                        <input type="hidden" name="pageSize" value="@ViewBag.pageSize" />
                        <div class="input-group mr-4">
                            <input style="border-radius:20px;" class="form-control mr-4" type="search" placeholder="Buscar por jogos" aria-label="Search" name="searchTerm" id="searchTerm" onchange="submitSearch()">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success my-2 my-sm-0 visually-hidden" type="button" onclick="submitSearch()" />
                            </div>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Loja" asp-action="Index">Lojas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Jogo" asp-action="Index">Jogos</a>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                </li>
                -->
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Noticia" asp-action="Index">Noticias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index" style="@(_sessao.BuscarSessaoDoUsuario() != null ? "display: none;" : "")">Login</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-danger" asp-area="" asp-controller="Login" asp-action="Sair" style="@(_sessao.BuscarSessaoDoUsuario() != null ? "" : "display: none;")">Sair</a>
                </li>
            </ul>
        </div>
    </div>
</nav>